更新API说明
EggLinks/DanhengServer-Public pull request #7
Opened 2024-07-10 16:14 UTC by wyxw688

更新API是说明

2024-07-10 16:18 UTC, StopWuyu requested changes
move the API doc to a single file plz(./docs/MuipAPI_zh-CN.md...)
and leave a link here

2024-07-10 19:42 UTC, YinCQL commented
你可以顺便将所有README里的 [繁中](docs/README_zh-CN.md) 改为 [繁中](docs/README_zh-TW.md) 吗

2024-07-11 06:07 UTC, EggLink commented on README.md
> +3. Download Resources[https://github.com/Dimbreath/StarRailData](https://github.com/Dimbreath/StarRailData) and unzip to the same directory `Resources`, then download Configuration from the project a
Turn to https://github.com/EggLinks/DanhengServer-Resources and get the andy's res
overwrite the res of dim once with Andy's res ( only Config folder, ExcelOutput should use Dim's )

2024-07-11 06:09 UTC, StopWuyu approved these changes

2024-07-11 06:40 UTC, merged